from __future__ import annotations


AI_RUNTIME_VERSION = "2"
RVC_CU128_RUNTIME_VERSION = "1"
RVC_DIRECTML_RUNTIME_VERSION = "1"
RVC_ROCM_WINDOWS_RUNTIME_VERSION = "2"

RVC_RUNTIME_PROFILE_VERSIONS = {
    "cu128": RVC_CU128_RUNTIME_VERSION,
    "directml": RVC_DIRECTML_RUNTIME_VERSION,
    "rocm-win": RVC_ROCM_WINDOWS_RUNTIME_VERSION,
}
